//! In phase 1 of the algorithm, the cube is brought from its state into the
//! subgroup generated by <L, R, F2, B2, U2, D2>. This subgroup is the set of
//! states where all corners and edges are correctly oriented, and the LR-slice
//! edges are in the LR-slice.

use std::{
    collections::HashMap,
    io::{Read, Write},
};

use num::{Zero, range, traits::FromBytes};

use crate::model::{
    bits::{self, serialize_array},
    coord::Coord,
    state::State,
    sym::Symmetries,
};

/// Sym-coords are coordinates that are reduced by symmetries. This allows to have more
/// compact move tables and pruning tables.
/// For a given symmetry equivalence class, a single coordinate is used to represent the whole class.
/// To do so, element with the smallest coordinate from the equivalence class is taken as the representative
/// for its class. A mapping is then built from the raw coordinate of the representative to the
/// index of the equivalence class.
pub struct SymCoordTable<C: Coord> {
    raw_to_repr: HashMap<C::Raw, C::Sym>,
    repr_to_raw: Vec<C::Raw>,
}

impl<C: Coord> SymCoordTable<C> {
    pub fn build(sym: &Symmetries) -> Self {
        let mut raw_to_repr = HashMap::new();
        for c in range(Zero::zero(), C::RAW_SIZE) {
            let s = C::from_repr(c).sample_state();
            let raw = (0..sym.size())
                .map(|i| C::from_state(&sym.conj_inv(s, i)).repr())
                .min()
                .unwrap();
            if !raw_to_repr.contains_key(&raw) {
                raw_to_repr.insert(
                    raw,
                    num::cast::<usize, C::Sym>(raw_to_repr.len())
                        .expect("sym-coord type too small to hold the coordinates"),
                );
            }
        }
        assert_eq!(raw_to_repr.len(), C::sym_to_usize(C::SYM_SIZE));
        let mut repr_to_raw = vec![Zero::zero(); raw_to_repr.len()];
        for (&raw, &sym) in raw_to_repr.iter() {
            repr_to_raw[C::sym_to_usize(sym)] = raw;
        }
        Self {
            raw_to_repr,
            repr_to_raw,
        }
    }

    pub fn coord(&self, state: State, sym: &Symmetries) -> C::Raw {
        for i in 0..sym.size() {
            let raw = C::from_state(&sym.conj_inv(state, i)).repr();
            if let Some(&coord) = self.raw_to_repr.get(&raw) {
                return C::pack_sym_coord(coord, i);
            }
        }
        unreachable!("a state always has a sym-coord");
    }

    pub fn repr(&self, coord: C::Sym) -> State {
        let raw = self.repr_to_raw[C::sym_to_usize(coord)];
        C::from_repr(raw).sample_state()
    }

    pub fn size(&self) -> usize {
        self.repr_to_raw.len()
    }

    pub fn deserialize<Source: Read>(source: &mut Source) -> std::io::Result<Self>
    where
        for<'a> &'a [u8]: TryInto<&'a <C::Raw as FromBytes>::Bytes>,
    {
        let mut buffer = Vec::new();
        source.read_to_end(&mut buffer)?;
        let sym_to_raw = bits::deserialize_array::<C::Raw>(&buffer);
        let mut raw_to_sym = HashMap::new();
        for (i, &raw) in sym_to_raw.iter().enumerate() {
            raw_to_sym.insert(raw, C::usize_to_sym(i));
        }
        Ok(Self {
            raw_to_repr: raw_to_sym,
            repr_to_raw: sym_to_raw,
        })
    }

    pub fn serialize<Sink: Write>(&self, sink: &mut Sink) -> std::io::Result<()> {
        sink.write_all(&serialize_array(&self.repr_to_raw))
    }
}

pub struct SymCoordMoveTable<C: Coord> {
    move_table: Vec<C::Raw>,
}

impl<C: Coord> SymCoordMoveTable<C> {
    pub fn build(sym_coord: &SymCoordTable<C>, sym: &Symmetries) -> Self {
        let mut move_table = Vec::with_capacity(sym_coord.size() * State::BASIC_MOVES.len());
        for coord in range(Zero::zero(), C::usize_to_sym(sym_coord.size())) {
            let state = sym_coord.repr(coord);
            for i in 0..State::BASIC_MOVES.len() {
                println!("{coord} {i}{state}{}", State::BASIC_MOVES[i] * state);
                move_table.push(sym_coord.coord(State::BASIC_MOVES[i] * state, sym));
            }
        }
        Self { move_table }
    }

    pub fn coord_mv(&self, coord: C::Raw, mv: u8, sym: &Symmetries) -> C::Raw {
        let (i, j) = C::unpack_sym_coord(coord);
        let mv = sym.conj_inv_mv(mv, j);
        let coord = self.move_table[18 * C::sym_to_usize(i) + mv as usize];
        let (k, l) = C::unpack_sym_coord(coord);
        C::pack_sym_coord(k, sym.prod(l, j))
    }
}

#[cfg(test)]
mod tests {

    use crate::model::{
        coord::{CO, Coord, EOLR, LR},
        sym::Symmetries,
        sym_coord::{SymCoordMoveTable, SymCoordTable},
    };

    #[test]
    fn test_sym_coords() {
        fn test<C: Coord>(sym: &Symmetries) {
            let table = SymCoordTable::<C>::build(sym);
            for i in 0..table.size() {
                assert_eq!(C::usize_to_sym(i), table.raw_to_repr[&table.repr_to_raw[i]]);
            }
            let _ = SymCoordMoveTable::build(&table, sym);
        }
        let sym = Symmetries::sub16();
        test::<CO>(&sym);
        // test::<EO>(&sym); The EO coord is not really compatible with the symmetries. Needs investigation.
        test::<LR>(&sym);
        test::<EOLR>(&sym);
    }
}
