//! A symmetry is a movement of the cube as a whole.
//! Some cube states are equivalent to one another with respect to some symmetry.
//! Intuitively, A is equivalent to B if it is possible to perform it with a change
//! of perspective (i.e. a symmetry), with the same result.
//! Or, in mathematical terms, A is equivalent to B if there is a symmetry S such that
//! `B = S^-1 * A * S`
//! The set of symmetries for a cube contains 48 unique symmetries that can be generated
//! by four elements.

use std::collections::HashMap;

use itertools::iproduct;

use crate::core::state::State;

/// Rotating the whole cube clockwise around the L axis (same direction as the face turn L).
pub const ROT_L: State = State {
    corners: 0b_10100_10000_00100_00000_11100_11000_01100_01000,
    edges: 0b_01110_01100_01010_01000_10010_10000_10110_10100_00101_00001_00111_00011,
};

/// Rotating the whole cube clockwise around the LBD corner.
pub const ROT_LBD: State = State {
    corners: 0b_11110_10101_01101_00110_11001_10010_01010_00001,
    edges: 0b_00110_00100_00010_00000_10111_10011_10101_10001_01111_01011_01101_01001,
};

/// Mirroring the whole cube across the origin.
pub const ROT_U2: State = State {
    corners: 0b_01000_01100_00000_00100_11000_11100_10000_10100,
    edges: 0b_10100_10110_10000_10010_01000_01010_01100_01110_00010_00000_00110_00100,
};

/// Mirroring the whole cube across the LR axis.
pub const MIR_LR: State = State {
    corners: 0b_11000_11100_10000_10100_01000_01100_00000_00100 | (1 << 63),
    edges: 0b_10100_10110_10000_10010_01100_01110_01000_01010_00110_00100_00010_00000,
};

pub struct Symmetries {
    elems: Vec<State>,
    inv: Vec<u8>,
    comp: Vec<u8>,
    conj_inv_mv: Vec<u8>,
}

impl Symmetries {
    /// Generates all the symmetries that are generated by repeated powers
    /// of the given generators.
    pub fn generate<const N: usize>(gens: [State; N]) -> Self {
        let mut elems = Vec::with_capacity(48);
        let mut end = [State::ID; N];
        let mut state = State::ID;
        let mut top = N - 1;
        loop {
            if top == N - 1 {
                elems.push(state);
                state = state * gens[top];
            }
            if state == end[top] {
                if top == 0 {
                    break;
                }
                top -= 1;
                state = state * gens[top];
            } else if top < N - 1 {
                end.iter_mut().skip(top + 1).for_each(|e| *e = state);
                top = N - 1;
            }
        }

        let mut elem_to_idx = HashMap::with_capacity(elems.len());
        for (i, e) in elems.iter().enumerate() {
            elem_to_idx.insert(e, i as u8);
        }
        let mut sym = Self {
            elems: elems.clone(),
            inv: Vec::with_capacity(elems.len()),
            comp: Vec::with_capacity(elems.len() * elems.len()),
            conj_inv_mv: Vec::with_capacity(18 * elems.len()),
        };
        for elem in elems.iter() {
            sym.inv.push(elem_to_idx[&elem.inv()]);
        }
        for (i, j) in iproduct!(0..elems.len(), 0..elems.len()) {
            sym.comp.push(elem_to_idx[&(elems[i] * elems[j])]);
        }
        let state_to_mv: HashMap<_, _> =
            (0..18).map(|i| (State::BASIC_MOVES[i], i as u8)).collect();
        for (i, m) in iproduct!(0..elems.len(), 0..18) {
            sym.conj_inv_mv
                .push(state_to_mv[&sym.conj_inv(State::BASIC_MOVES[m], i as u8)]);
        }
        sym
    }

    /// All 48 symmetries of the cube group. They form a group and are all unique.
    pub fn all() -> Self {
        Self::generate([ROT_L, ROT_U2, MIR_LR, ROT_LBD])
    }

    /// A subgroup of symmetries that preserve edge and corner orientations, as well as the LR slice edges
    pub fn sub16() -> Self {
        Self::generate([ROT_L, ROT_U2, MIR_LR])
    }

    /// The length of this symmetry group
    pub fn size(&self) -> u8 {
        self.elems.len() as u8
    }

    /// The symmetry at the given index
    pub fn sym(&self, s: u8) -> State {
        self.elems[s as usize]
    }

    /// The inverse symmetry at the given index
    pub fn inv(&self, s: u8) -> u8 {
        self.inv[s as usize]
    }

    /// The product of symmetries with the given indices
    pub fn prod(&self, s1: u8, s2: u8) -> u8 {
        self.comp[(8 * s1 + s2) as usize]
    }

    /// The state resulting from applying this state under the given symmetry.
    pub fn conj(&self, state: State, s: u8) -> State {
        self.sym(self.inv(s)) * state * self.sym(s)
    }

    /// The state resulting from applying this state under the inverse of the given symmetry.
    pub fn conj_inv(&self, state: State, s: u8) -> State {
        self.sym(s) * state * self.sym(self.inv(s))
    }

    /// The conjugated move using the given symmetry.
    pub fn conj_inv_mv(&self, mv: u8, s: u8) -> u8 {
        self.conj_inv_mv[(s * 18 + mv) as usize]
    }

    /// The representative state for the sym-class of the given state.
    /// It returns an equivalent state, up to a symmetry. The index of the symmetry is also given.
    /// The representative is chosen as the smallest state that belongs to the equivalence class.
    pub fn repr(&self, state: State) -> (State, u8) {
        (0..self.elems.len() as u8)
            .map(|i| (self.conj_inv(state, i), i))
            .min_by_key(|(s, _)| *s)
            .unwrap()
    }
}

#[cfg(test)]
mod tests {
    use std::collections::{HashMap, HashSet};

    use itertools::join;

    use crate::core::{
        moves::{Direction, Face, Move},
        state::State,
        sym::{MIR_LR, ROT_L, ROT_LBD, ROT_U2, Symmetries},
    };

    #[test]
    fn mirror_composition() {
        let a: State = Move::L.into();
        let b = MIR_LR;
        let c: State = Move::D.into();
        let d = b.inv();
        let e: State = Move::F.into();
        let rhs = Move::L * Move::D_ * Move::F;
        assert_eq!((((a * b) * c) * d) * e, rhs);
        assert_eq!(a * (b * (c * (d * e))), rhs);
        assert_eq!(((a * (b * c)) * d) * e, rhs);
    }

    fn test_conj(mv1: Move, mv2: Move, sym: State) {
        assert_eq!(sym.inv() * mv2 * sym, mv1.into());
    }

    fn test_order(state: State, order: usize) {
        let mut power = State::ID;
        for _ in 0..order {
            power = power * state;
        }
        assert_eq!(power, State::ID);
    }

    #[test]
    fn rot_lbd() {
        test_conj(Move::U, Move::F, ROT_LBD);
        test_conj(Move::F, Move::R, ROT_LBD);
        test_conj(Move::R, Move::U, ROT_LBD);
        test_conj(Move::L, Move::D, ROT_LBD);
        test_conj(Move::B, Move::L, ROT_LBD);
        test_conj(Move::D, Move::B, ROT_LBD);
        test_order(ROT_LBD, 3);
    }

    #[test]
    fn rot_l() {
        test_conj(Move::L, Move::L, ROT_L);
        test_conj(Move::R, Move::R, ROT_L);
        test_conj(Move::U, Move::F, ROT_L);
        test_conj(Move::F, Move::D, ROT_L);
        test_conj(Move::D, Move::B, ROT_L);
        test_conj(Move::B, Move::U, ROT_L);
        test_order(ROT_L, 4);
    }

    #[test]
    fn rot_u2() {
        test_conj(Move::U, Move::U, ROT_U2);
        test_conj(Move::D, Move::D, ROT_U2);
        test_conj(Move::L, Move::R, ROT_U2);
        test_conj(Move::R, Move::L, ROT_U2);
        test_conj(Move::B, Move::F, ROT_U2);
        test_conj(Move::F, Move::B, ROT_U2);
        test_order(ROT_U2, 2);
    }

    #[test]
    fn mir_lr() {
        test_conj(Move::L, Move::R_, MIR_LR);
        test_conj(Move::R, Move::L_, MIR_LR);
        test_conj(Move::D, Move::D_, MIR_LR);
        test_conj(Move::U, Move::U_, MIR_LR);
        test_conj(Move::B, Move::B_, MIR_LR);
        test_conj(Move::F, Move::F_, MIR_LR);
        test_order(MIR_LR, 2);
    }

    #[test]
    fn all_symmetries_form_a_group() {
        let _ = Symmetries::all();
    }

    #[test]
    fn reduced_symmetries_form_a_group() {
        let _ = Symmetries::sub16();
    }

    #[test]
    fn state_repr() {
        let sym = Symmetries::all();
        let mut reprs = HashMap::new();
        let mut single_turns = Vec::new();
        let mut double_turns = Vec::new();
        for face in Face::ALL_FACES {
            single_turns.push(Move {
                face,
                dir: Direction::Clockwise,
            });
            single_turns.push(Move {
                face,
                dir: Direction::CounterClockwise,
            });
            double_turns.push(Move {
                face,
                dir: Direction::HalfTurn,
            });
            for dir in [
                Direction::Clockwise,
                Direction::CounterClockwise,
                Direction::HalfTurn,
            ] {
                let mv = Move { face, dir };
                let state: State = mv.into();
                let (repr, sidx) = sym.repr(state);
                assert_eq!(state, sym.conj(repr, sidx));
                assert!(repr.valid());
                reprs.entry(repr).or_insert(Vec::new()).push(mv);
            }
        }
        for v in reprs.values() {
            println!("{}", join(v.iter().map(Move::to_string), " "));
        }
        assert_eq!(
            reprs.values().cloned().collect::<HashSet<_>>(),
            HashSet::from([single_turns, double_turns])
        );
    }
}
