//! In phase 1 of the algorithm, the cube is brought from its state into the
//! subgroup generated by <L, R, F2, B2, U2, D2>. This subgroup is the set of
//! states where all corners and edges are correctly oriented, and the LR-slice
//! edges are in the LR-slice.

use crate::model::{coord::{Coord, EO, LR}, state::State};

/// Combined EO + LR coordinates
#[derive(Debug, PartialEq, Eq)]
pub struct EOLR {
    coord: u32,
}

impl Coord for EOLR {
    type Repr = u32;

    const COUNT: Self::Repr = EO::COUNT as u32 * LR::COUNT as u32;

    fn from_state(state: &State) -> Self {
        let eo = EO::from_state(state);
        let lr = LR::from_state(state);
        Self { coord: (eo.repr() as u32) * (LR::COUNT as u32) + lr.repr() as u32 }
    }

    fn from_repr(repr: Self::Repr) -> Self {
        Self { coord: repr }
    }

    fn repr(&self) -> Self::Repr {
        self.coord
    }

    fn sample_state(&self) -> State {
        let eo = EO::from_repr((self.coord / (LR::COUNT as u32)) as u16);
        let lr = LR::from_repr((self.coord % (LR::COUNT as u32)) as u16);
        eo.sample_state() * lr.sample_state()
    }
}
